services:
    web:
        image: jakubboucek/lamp-devstack-php:8.5
        environment:
            APACHE_DOCUMENT_ROOT: "/var/www/html/web/www"
            APP_DEBUG: 1
            TZ: Europe/Prague
        ports:
            - "127.0.0.1:8080:80"
        restart: always
        volumes:
            - ".:/var/www/html"

    mysqldb:
        image: jakubboucek/lamp-devstack-mysql:10.5
        environment:
            MARIADB_DATABASE: default
            MARIADB_ROOT_PASSWORD: devstack
            TZ: Europe/Prague
        ports:
            - "127.0.0.1:33060:3306"
        restart: always
        volumes:
            - "./.docker/mysql/data:/var/lib/mysql"

    adminer:
        image: adminer
        environment:
            ADMINER_DEFAULT_SERVER: mysqldb
            ADMINER_DESIGN: hever
            ADMINER_PLUGINS: edit-foreign backward-keys sql-gemini
        ports:
            - "8088:8080"
        restart: always
